//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GESHOTEL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cancelations
    {
        public int idCancelations { get; set; }
        public Nullable<decimal> HandlingFee { get; set; }
        public Nullable<int> TimeFrame { get; set; }
        public Nullable<decimal> MonantBefore { get; set; }
        public Nullable<decimal> MontantAfter { get; set; }
        public Nullable<double> PourcentageBefore { get; set; }
        public Nullable<double> PourcentageAfter { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> idCancelationRules { get; set; }
        public string Etat { get; set; }
        public Nullable<int> idHotel { get; set; }
    
        public virtual CancelationRules CancelationRules { get; set; }
    }
}
