//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GESHOTEL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChambreMaintenance
    {
        public Nullable<System.DateTime> Debut { get; set; }
        public Nullable<System.DateTime> Fin { get; set; }
        public string Chambre { get; set; }
        public string Type_de_Chambre { get; set; }
        public string Raison { get; set; }
        public string RaisonType { get; set; }
        public Nullable<int> idHotel { get; set; }
        public string Hotel { get; set; }
    }
}
