//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GESHOTEL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChambreReserver
    {
        public int ID { get; set; }
        public Nullable<int> idChambre { get; set; }
        public Nullable<int> idReservationType { get; set; }
        public Nullable<System.DateTime> DateArrive { get; set; }
        public Nullable<System.DateTime> DateDepart { get; set; }
        public Nullable<System.DateTime> DateCheckIn { get; set; }
        public Nullable<System.DateTime> DateCheckOut { get; set; }
        public Nullable<int> idPromotion { get; set; }
        public string EtatOperation { get; set; }
        public string Etat { get; set; }
        public Nullable<int> idHotel { get; set; }
        public string TypeOperation { get; set; }
        public string ReservationType { get; set; }
        public string DateCheckOutVC { get; set; }
    }
}
