//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GESHOTEL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clients
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Clients()
        {
            this.Reservations = new HashSet<Reservations>();
        }
    
        public int ID { get; set; }
        public string Civilite { get; set; }
        public string Noms { get; set; }
        public string Prenoms { get; set; }
        public string Sexe { get; set; }
        public string Addresse { get; set; }
        public Nullable<int> idPays { get; set; }
        public Nullable<int> Ville { get; set; }
        public Nullable<int> Quartier { get; set; }
        public Nullable<int> Commune { get; set; }
        public string AddressePostale { get; set; }
        public string Telephone { get; set; }
        public string Mobile { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> DateNaissance { get; set; }
        public Nullable<int> Nationalite { get; set; }
        public string PaiementMethode { get; set; }
        public string LieuNaissance { get; set; }
        public Nullable<int> IDType { get; set; }
        public string Numero { get; set; }
        public string Etat { get; set; }
        public Nullable<int> idHotel { get; set; }
    
        public virtual Communes Communes { get; set; }
        public virtual IDTypes IDTypes { get; set; }
        public virtual Nationalités Nationalités { get; set; }
        public virtual Pays Pays { get; set; }
        public virtual Quartiers Quartiers { get; set; }
        public virtual Villes Villes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reservations> Reservations { get; set; }
    }
}
