//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GESHOTEL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailPaiements
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> DatePaiement { get; set; }
        public Nullable<double> Montant { get; set; }
        public int idTransaction { get; set; }
        public string Numero { get; set; }
        public string NomBanque { get; set; }
        public string NomsReceveur { get; set; }
        public Nullable<int> idMethodePaiement { get; set; }
        public string Etat { get; set; }
        public Nullable<int> idHotel { get; set; }
    
        public virtual MethodePaiements MethodePaiements { get; set; }
        public virtual Transactions Transactions { get; set; }
    }
}
