//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GESHOTEL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailTransactions
    {
        public int ID { get; set; }
        public int ProduitID { get; set; }
        public int TransactionID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Descriptions { get; set; }
        public Nullable<decimal> prix { get; set; }
        public Nullable<double> Quantite { get; set; }
        public Nullable<decimal> Montant { get; set; }
        public Nullable<decimal> Reduction { get; set; }
        public Nullable<decimal> ReductionAuto { get; set; }
        public string Commentaire { get; set; }
        public string Type { get; set; }
        public string Etat { get; set; }
        public Nullable<int> idHotel { get; set; }
    
        public virtual Produits Produits { get; set; }
        public virtual Transactions Transactions { get; set; }
    }
}
