//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GESHOTEL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetatilDepenses
    {
        public int idDetailDepense { get; set; }
        public Nullable<int> idSousRubrique { get; set; }
        public Nullable<int> idTransaction { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Description { get; set; }
        public Nullable<double> Quantite { get; set; }
        public Nullable<double> PrixUnitaire { get; set; }
        public Nullable<double> Montant { get; set; }
        public Nullable<int> IdHotel { get; set; }
    
        public virtual Sous_Rubriques Sous_Rubriques { get; set; }
        public virtual Transactions Transactions { get; set; }
    }
}
