//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GESHOTEL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employees()
        {
            this.Transactions = new HashSet<Transactions>();
        }
    
        public int idEmploye { get; set; }
        public string EmpNum { get; set; }
        public string Nom { get; set; }
        public string Prenoms { get; set; }
        public Nullable<System.DateTime> DateNaisssance { get; set; }
        public string LieuNaissance { get; set; }
        public string Sexe { get; set; }
        public string Cel { get; set; }
        public string Addresse { get; set; }
        public string PersonneAContacte { get; set; }
        public string CelAContacte { get; set; }
        public string AddresseAContacte { get; set; }
        public string RelationParental { get; set; }
        public Nullable<int> NbreEnfant { get; set; }
        public byte[] Photo { get; set; }
        public Nullable<double> Salaire { get; set; }
        public string Etat { get; set; }
        public Nullable<int> idTypeEmployees { get; set; }
        public Nullable<int> IdHotel { get; set; }
    
        public virtual TypeEmployees TypeEmployees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transactions> Transactions { get; set; }
    }
}
