//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GESHOTEL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelInfo
    {
        public int idHotel { get; set; }
        public string Noms { get; set; }
        public string AddressPostal { get; set; }
        public string Address { get; set; }
        public Nullable<int> idPays { get; set; }
        public Nullable<int> idVilles { get; set; }
        public Nullable<int> idCommune { get; set; }
        public Nullable<int> idQuartier { get; set; }
        public string Telephone { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string Etat { get; set; }
    
        public virtual Communes Communes { get; set; }
        public virtual Pays Pays { get; set; }
        public virtual Quartiers Quartiers { get; set; }
        public virtual Villes Villes { get; set; }
    }
}
