//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GESHOTEL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListeStatChambre
    {
        public string ReservationType { get; set; }
        public string TypeChambres { get; set; }
        public string Chambre { get; set; }
        public Nullable<int> Total { get; set; }
        public Nullable<int> Passage { get; set; }
        public Nullable<int> Nuit { get; set; }
        public Nullable<int> Sejour { get; set; }
        public Nullable<int> Maintenance { get; set; }
        public Nullable<int> Annuler { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> DateArrive { get; set; }
    }
}
