//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GESHOTEL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListDepense
    {
        public int ID { get; set; }
        public string Objet { get; set; }
        public Nullable<System.DateTime> DateTransaction { get; set; }
        public Nullable<double> Montant { get; set; }
        public Nullable<double> SOLDE { get; set; }
        public string Rubrique { get; set; }
        public Nullable<int> idRegistre { get; set; }
        public Nullable<int> idHotel { get; set; }
        public string TypeTransaction { get; set; }
    }
}
