//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GESHOTEL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OperationRules
    {
        public int idOperationRules { get; set; }
        public int idReservationTypes { get; set; }
        public int idTypeChambre { get; set; }
        public int idRule { get; set; }
        public int idReduction { get; set; }
        public Nullable<int> Quantite { get; set; }
        public string Etat { get; set; }
        public Nullable<int> idHotel { get; set; }
    
        public virtual Reductions Reductions { get; set; }
        public virtual ReservationTypes ReservationTypes { get; set; }
        public virtual Rules Rules { get; set; }
        public virtual TypeChambres TypeChambres { get; set; }
    }
}
