//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GESHOTEL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parametres
    {
        public int IdParametre { get; set; }
        public Nullable<int> FacNum { get; set; }
        public Nullable<int> AONum { get; set; }
        public Nullable<int> SocNum { get; set; }
        public Nullable<int> CptNum { get; set; }
        public Nullable<int> TransNum { get; set; }
        public Nullable<int> LocNum { get; set; }
        public Nullable<int> CliNum { get; set; }
        public Nullable<int> ProdNum { get; set; }
        public Nullable<int> FourNum { get; set; }
    }
}
