//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GESHOTEL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produits
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Produits()
        {
            this.DetailTransactions = new HashSet<DetailTransactions>();
        }
    
        public int ID { get; set; }
        public string Libelle { get; set; }
        public string Reference { get; set; }
        public string TypeProduit { get; set; }
        public Nullable<decimal> PrixUnitaire { get; set; }
        public Nullable<int> Stock { get; set; }
        public Nullable<int> Conditionnement { get; set; }
        public Nullable<int> Categorie { get; set; }
        public Nullable<int> idHotel { get; set; }
        public string Etat { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual Conditionnements Conditionnements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetailTransactions> DetailTransactions { get; set; }
    }
}
