//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GESHOTEL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecuReservations
    {
        public int ID { get; set; }
        public string TransactionNumero { get; set; }
        public Nullable<System.DateTime> DateTransaction { get; set; }
        public string ReservationType { get; set; }
        public string TypeChambres { get; set; }
        public string Chambre { get; set; }
        public Nullable<System.DateTime> DateArrive { get; set; }
        public Nullable<System.DateTime> DateDepart { get; set; }
        public Nullable<int> NbreNuit { get; set; }
        public Nullable<int> NbreAdult { get; set; }
        public string Noms { get; set; }
        public string Prenoms { get; set; }
        public string Sexe { get; set; }
        public string Addresse { get; set; }
        public string Pays { get; set; }
        public string Nationalités { get; set; }
        public string Villes { get; set; }
        public string Communes { get; set; }
        public string Quartiers { get; set; }
        public string Telephone { get; set; }
        public string Mobile { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public Nullable<decimal> TotalTTC { get; set; }
        public Nullable<decimal> TotalPaye { get; set; }
        public Nullable<decimal> TotalReste { get; set; }
        public Nullable<decimal> Reduction { get; set; }
        public string NomHotel { get; set; }
        public Nullable<decimal> TotalHT { get; set; }
        public Nullable<decimal> TVA { get; set; }
    }
}
