//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GESHOTEL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registres
    {
        public int idRegistre { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> DateDebut { get; set; }
        public Nullable<System.DateTime> DateFermeture { get; set; }
        public Nullable<decimal> SoldeInitiale { get; set; }
        public Nullable<decimal> SoldeFinale { get; set; }
        public Nullable<decimal> SoldeCalcule { get; set; }
        public Nullable<decimal> TransactionCash { get; set; }
        public string State { get; set; }
        public Nullable<int> idUtilisateur { get; set; }
        public Nullable<int> idHotel { get; set; }
    }
}
