//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GESHOTEL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReservationTypes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReservationTypes()
        {
            this.OperationRules = new HashSet<OperationRules>();
            this.Reservations = new HashSet<Reservations>();
            this.TypePrix = new HashSet<TypePrix>();
        }
    
        public int ID { get; set; }
        public string ReservationType { get; set; }
        public Nullable<bool> isFixe { get; set; }
        public Nullable<System.TimeSpan> HeureDepart { get; set; }
        public Nullable<System.TimeSpan> HeureFin { get; set; }
        public Nullable<int> Heure { get; set; }
        public string Couleur { get; set; }
        public string Etat { get; set; }
        public Nullable<int> idHotel { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OperationRules> OperationRules { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reservations> Reservations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TypePrix> TypePrix { get; set; }
    }
}
