//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GESHOTEL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transactions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Transactions()
        {
            this.DetailPaiements = new HashSet<DetailPaiements>();
            this.DetailTransactions = new HashSet<DetailTransactions>();
            this.DetatilDepenses = new HashSet<DetatilDepenses>();
            this.TranReductions = new HashSet<TranReductions>();
        }
    
        public int ID { get; set; }
        public Nullable<int> idReservation { get; set; }
        public string TransactionNumero { get; set; }
        public string Beneficiaire { get; set; }
        public string Objet { get; set; }
        public Nullable<decimal> TotalHT { get; set; }
        public Nullable<decimal> TotalReste { get; set; }
        public Nullable<decimal> TotalPaye { get; set; }
        public string Etat { get; set; }
        public Nullable<int> idFournisseur { get; set; }
        public Nullable<System.DateTime> DateTransaction { get; set; }
        public string TypeTransaction { get; set; }
        public Nullable<decimal> TotalTTC { get; set; }
        public Nullable<decimal> TVA { get; set; }
        public Nullable<int> idRegistre { get; set; }
        public Nullable<decimal> Reduction { get; set; }
        public Nullable<int> idHotel { get; set; }
        public Nullable<int> idEmployee { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetailPaiements> DetailPaiements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetailTransactions> DetailTransactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetatilDepenses> DetatilDepenses { get; set; }
        public virtual Employees Employees { get; set; }
        public virtual Fournisseurs Fournisseurs { get; set; }
        public virtual Reservations Reservations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TranReductions> TranReductions { get; set; }
    }
}
